[package]
name = "iota_interaction_ts"
version = "1.5.0"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity", "wasm"]
license = "Apache-2.0"
publish = false
readme = "README.md"
resolver = "2"
description = "identity_iota_interaction Adapters using Web Assembly bindings."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { version = "1.0.94", features = ["std"] }
async-trait = { version = "0.1", default-features = false }
bcs = "0.1.6"
bls12_381_plus = "0.8.17"
cfg-if = "1.0.0"
console_error_panic_hook = { version = "0.1" }
eyre = "0.6.12"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "5f2c63266a065996d53f98156f0412782b468597", package = "fastcrypto" }
futures = { version = "0.3" }
identity_core = { version = "=1.5.0", path = "../../../identity_core" }
identity_iota_interaction = { version = "=1.5.0", path = "../../../identity_iota_interaction", default-features = false }
js-sys = { version = "0.3.61" }
secret-storage = { git = "https://github.com/iotaledger/secret-storage.git", default-features = false, tag = "v0.2.0" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json.workspace = true
serde_repr = { version = "0.1", default-features = false }
thiserror.workspace = true
# Want to use the nice API of tokio::sync::RwLock for now even though we can't use threads.
tokio = { version = "1.29", default-features = false, features = ["sync"] }
tsify = "0.4.5"
wasm-bindgen = { version = "0.2.100", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4", default-features = false }
zkryptium = "0.2.2"

[dev-dependencies]
rand = "0.8.5"

[target.'cfg(all(target_arch = "wasm32", not(target_os = "wasi")))'.dependencies]
getrandom = { version = "0.2", default-features = false, features = ["js"] }
instant = { version = "0.1", default-features = false, features = ["wasm-bindgen"] }

[lints.clippy]
# can be removed as soon as fix has been added to clippy
# see https://github.com/rust-lang/rust-clippy/issues/12377
empty_docs = "allow"

[features]
keytool-signer = ["identity_iota_interaction/keytool-signer"]
