name: "publish-wasm"
description: "Publishes Wasm bindings to npm"
inputs:
  tag:
    description: "Which npm tag to publish under e.g. `dev`, will default to `latest`"
    required: false
  input-artifact-name:
    description: "Name used for the input Wasm build artifact"
    required: true
  working-directory:
    description: "Directory to publish from"
    required: true
  dry-run:
    description: "'true' = only log potential result; 'false' = publish'"
    required: true
  GH_TOKEN:
    description: "GH_TOKEN to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: "lts/*"
        registry-url: "https://registry.npmjs.org"

    - name: Download bindings/wasm artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.input-artifact-name }}
        path: bindings/wasm/iota_interaction_ts

    - name: Publish WASM bindings to NPM
      shell: sh
      working-directory: ${{ inputs.working-directory }}
      env:
          GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      # will publish 'latest' tag if no tag is passed
      run: |
        echo "dry-run: '${{ inputs.dry-run }}'"
        echo "tag: '${{ inputs.tag }}'"
        npm publish $(if [ "${{ inputs.dry-run }}" != "false" ]; then echo --dry-run; fi) $(if [ ${{ inputs.tag }} != '' ]; then echo --tag ${{ inputs.tag }}; fi) --access public
