[advisories]
ignore = [
    "RUSTSEC-2024-0437", # protobuf uncontrolled recursion https://github.com/iotaledger/iota/issues/5861
    "RUSTSEC-2021-0127", # serde_cbor is unmaintained https://github.com/iotaledger/identity.rs/issues/518
    "RUSTSEC-2023-0052", # temporary ignore until fix is provided
    "RUSTSEC-2023-0065", # temporary ignore until fix is provided
    "RUSTSEC-2023-0071", # temporary ignore until fix is provided
    "RUSTSEC-2024-0437", # temporary ignore until fix is provided
    "RUSTSEC-2025-0023", # tokio; to be updated from upstream
]
