[advisories]
ignore = [
  "RUSTSEC-2025-0023", # tokio; to be updated from upstream
  "RUSTSEC-2021-0145", #
  "RUSTSEC-2024-0320", # to be fixed upstream
  "RUSTSEC-2024-0370", # to be fixed upstream
  "RUSTSEC-2024-0436", #
  "RUSTSEC-2024-0384", # instant unmaintained
  "RUSTSEC-2021-0141", # dotenv unmaintained
  "RUSTSEC-2024-0388",
  "RUSTSEC-2024-0375",
  "RUSTSEC-2021-0139",
  "RUSTSEC-2023-0071",
  "RUSTSEC-2024-0437",
]
