[package]
name = "product-core"
version = "0.8.10"
edition.workspace = true
keywords = ["iota", "trust-framework"]
license.workspace = true
readme = "./README.md"
description = "Sources shared by IOTA products."

[dependencies]
iota-sdk = { workspace = true, features = ["move-types"] }
thiserror.workspace = true
url.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
secret-storage.workspace = true
futures = "0.3.32"
cynic = "3.13.2"

[dev-dependencies]
tokio.workspace = true
anyhow.workspace = true
